### PR TITLE
New theme 

### PR DESCRIPTION
**Pull request by Jamesinorbit**
Please can I add my theme Epic Retro Noir to your fantastic app? It's my take on the classic Epic Noir theme. I think I've done everything correctly. Never used GitHub before..many thanks and I appreciate you creating this excellent front end.

James

### CODE REVIEW

**Comment by Post-Mortem** [comment]
Hello. I'll be helping you.  You left waifus in your root folder

**Review by Post-Mortem — CHANGES_REQUESTED** [review]
Hello. I'll be helping you mate. You still need to create an index file inside your theme's folder. In it you'll specify the route for each image and it's file name. You edited the main themes index file. You don't need to touch that file

**Comment by Jamesinorbit** [comment]
thank you really appreciate you helping me

**Comment by Post-Mortem** [comment]
@Jamesinorbit no problem dude. This was my favorite theme back in the day. This is a beautiful work.

**Comment by Jamesinorbit** [comment]
Hi mate, just wanted to let you know the wallpapers aren't loading in the app currently. Something about a json serialization exception...I think it's to do with what you said about waifus and me messing with the root json file. Sorry mate for messing it up. Hope its easy for you to sort

**Comment by Jamesinorbit** [comment]
Hi mate, I can see the theme in the list now in the app (AWESOME!) but it won't download for some reason. Think something is up with my index file in the EpicRetroNoir folder? Sorry if I'm stating the obvious and you are still working on it...

**Comment by Jamesinorbit** [comment]
Hi mate. I do have a thumbnail image in the folder named thumbnail.png. Can we use that please?

**Comment by Post-Mortem** [comment]
@Jamesinorbit hello brother, everything should be working now. Please clear your daijisho app cache, and try again.

**Comment by Jamesinorbit** [comment]
LEGEND! mate one thing. Famicom Disk system is using the default wallpaper. I think I forgot to add it to my index file. Could u please add it in and point to fds.png please.

**Comment by Post-Mortem** [comment]
> LEGEND! mate one thing. Famicom Disk system is using the default wallpaper. I think I forgot to add it to my index file. Could u please add it in and point to fds.png please.

Done!

**Comment by Jamesinorbit** [comment]
Have a good one mate

**Comment by Post-Mortem** [comment]
> Have a good one mate

@Jamesinorbit you too brother, please go online on discord if you can. And go into the daijisho server. I'm going to ask for some edits to see if you could do some changes :P

**Comment by Jamesinorbit** [comment]
No worries. Have I messed some of them up? Do they need amending

**Comment by Jamesinorbit** [comment]
I tested it on rp2 and rp3 and a rg552 and a x18s so hopefully they are all good with the cropping etc.

**Pull request merged**
