### PR TITLE
6 new systems added

### PR DESCRIPTION
**Pull request by Post-Mortem**
New systems:

- wonderswan
- wonderswancolor
- sega game gear
- neogeo pocket
- neogeo pocket color
- supergrafx

and NDS wallpaper improvement.

### CODE REVIEW

**Comment by magneticchen** [comment]
Beautiful pack!

**Comment by Post-Mortem** [comment]
> Beautiful pack!

Thank you sensei 🙏

**Comment by magneticchen** [comment]
Definitely one of the best! ❤️

**Comment by Post-Mortem** [comment]
> Definitely one of the best! ❤️

I really appreciate it, thank you. 😁

**Pull request merged**
